

remote_theme: yaoyao-liu/minimal-light

# 基本信息
title: 丁佳乐
position: Ph.D. Candidate
affiliation: 浙江大学 | Zhejiang University
email: yorktown@zju.edu.cn

# 搜索引擎优化 (SEO)
keywords: 个人主页; 时空大数据; 人工智能; 深度学习; GeoAI; GIS; 云原生; 2026; 博士
description: 研究方向为时空大数据与人工智能 (GeoAI)，预计毕业时间2026年6月

# 链接
github_link: https://github.com/yorktownting/
linkedin: https://www.linkedin.com/in/jialeding-yorktown/
google_scholar: https://scholar.google.com/citations?hl=zh-CN&user=Sx-Nk64AAAAJ/
cv_link: ./assets/Curriculum_Vitae.pdf

# 图片路径
avatar: ./assets/img/avatar.png
favicon: ./assets/img/favicon.png
